public class JavaCatchKeyword {
  public static void main(String[] args) {
    //The catch keyword catches exceptions generated by try statements.
    //The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.
    //If an error occur, use try...catch to catch the error and execute some code to handle it:
    //
    try {
      int[] myNumbers = {1, 2, 3};

      System.out.println(myNumbers[10]);
    } catch (Exception e) {
      System.out.println("Something went wrong.");
    }
  }
}
